# Site settings
title: Program Hub Prototyping.
description: "Just some prototyping. Nothing to see here."
url: "http://www.open-curriculum.org" # the base hostname & protocol for your site
baseurl: /program-hub
permalink: pretty
# Build settings
markdown: kramdown
collections:
  exhibitions:
    output: true
    permalink: /exhibitions/:title.html