# Site settings
title: Jekyll + Materialize = <3
description: "Just when you didn't think Jekyll could get any better, it got materialized."
url: "http://www.open-curriculum.org/program-hub/" # the base hostname & protocol for your site
baseurl: /program-hub

# Build settings
markdown: kramdown
