title:              DMD

# Versioning
current_version: 1.5.0
foundation_version: 6.0.0

author:
  name:             username
  email:            user@domain.com
  github:           username
  twitter:          username

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
# source:             ./source Git Pages overrides this variable
# destination:        ./static

port:               9002
url: http://www.open-curriculum.org # the base hostname & protocol for your site
baseurl: "/program-hub"

# exclude this stuff when building the static site
exclude:            [
                      '.gitignore',
                      'README.md',
                      'Gemfile',
                      'Gemfile.lock',
                    ]

## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          Foundation-Jekyll
site_description :  Website description
site_copyright:     Copyright (c) 2016
site_url:           http://www.open-curriculum.org/program-hub
site_email:         site email
site_phone:         (555) 555-1234



# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/stylesheets
  style:            :compressed

 #  _   _     __      _______ _____       _______ _____ ____  _   _ 
 # | \ | |   /\ \    / /_   _/ ____|   /w\|__   __|_   _/ __ \| \ | |
 # |  \| |  /  \ \  / /  | || |  __   /  \  | |    | || |  | |  \| |
 # | . ` | / /\ \ \/ /   | || | |_ | / /\ \ | |    | || |  | | . ` |
 # | |\  |/ ____ \  /   _| || |__| |/ ____ \| |   _| || |__| | |\  |
 # |_| \_/_/    \_\/   |_____\_____/_/    \_\_|  |_____\____/|_| \_|

#Navigation
menuitems:
  - url: /program-hub/
    title: digital multimedia design
    slogan: We Meet You Where You Are
    mission: Inspiring leadership in design
    description: The Program
  - url: /program-hub/program/
    title: Program
  - url: /program-hub/about/
    title: About
  - url: /program-hub/apply/
    title: Apply
  - url: /program-hub/search/
    title: Search