import { defineContentConfig, defineCollection, z } from '@nuxt/content'

export default defineContentConfig({
  collections: {
    courses: defineCollection({
      type: 'page',
      source: 'courses/**/*.md',
      schema: z.object({
        title: z.string(),
        number: z.string(),
        credits: z.number().optional(),
        academicHome: z.string().optional(),
        courseType: z.array(z.string()).optional(),
        description: z.string().optional(),
        bulletinLink: z.string().optional(),
        pathwayList: z.array(z.string()).optional(),
        preReq: z.string().optional(),
        programCore: z.boolean().optional(),
        microSite: z.boolean().optional(),
        callout: z.string().optional(),
        imageUrl: z.string().optional(),
        microSiteDescription: z.string().optional(),
        offerings: z.array(z.object({
          data: z.string(),
          name: z.string(),
          current: z.boolean(),
          id: z.string(),
        })).optional(),
      }),
    }),
    pathways: defineCollection({
      type: 'page',
      source: 'pathways/**/*.md',
      schema: z.object({
        title: z.string(),
        slug: z.string().optional(),
        isActive: z.boolean().optional(),
        description: z.string().optional(),
        totalCredits: z.number().optional(),
        featured: z.boolean().optional(),
      }),
    }),
    exhibitions: defineCollection({
      type: 'page',
      source: 'exhibitions/**/*.md',
      schema: z.object({
        title: z.string(),
        class: z.string().optional(),
        year: z.number().optional(),
        semester: z.string().optional(),
        course: z.string().optional(),
        description: z.string().optional(),
        exhibitionImage: z.string().optional(),
        cardImageUrl: z.string().optional(),
        cardDescription: z.string().optional(),
        current: z.boolean().optional(),
        exhibition: z.string().optional(),
      }),
    }),
    faculty: defineCollection({
      type: 'page',
      source: 'faculty/**/*.md',
      schema: z.object({
        name: z.string(),
        titles: z.array(z.string()).optional(),
        email: z.string().optional(),
        imageUrl: z.string().optional(),
        facultyType: z.string().optional(),
        facultyDisplayLevel: z.number().optional(),
        displayOrder: z.number().optional(),
        role: z.array(z.string()).optional(),
        college: z.string().optional(),
        education: z.array(z.string()).optional(),
        published: z.boolean().optional(),
        coursesTaught: z.array(z.string()).optional(),
      }),
    }),
  },
})
